devices:
  hera:
    addr: xxx.xxx.xxx.xxx
    aionHome: /var/lib/aion
  iris:
    addr: xxx.xxx.xxx.xxx
    aionHome: /var/lib/aion
microservices:
  k8s-deployment-controller:
    scale: 1
    always: yes
    serviceAccount: controller-serviceaccount
    privileged: true
    volumeMountPathList:
      - /var/run/docker.sock:/var/run/docker.sock
    env:
      REGISTRY_USER: XXXX
      REGISTRY_PASSWORD: XXXX
    nextService:
      default:
        - name: get-response-of-container-deployment
  titaniadb-sentinel:
    scale: 1
    startup: yes
    always: yes
    serviceAccount: controller-serviceaccount
    env:
      MY_NODE_NAME: YOUR_DEVICE_NAME
  delete-container-image-from-edge:
    scale: 1
    multiple: yes
    serviceAccount: controller-serviceaccount
    env:
      REGISTRY_USER: XXXX
      REGISTRY_PASSWORD: XXXX
    nextService:
      default:
        - name: get-response-of-container-deployment
  get-response-of-container-deployment:
    scale: 1
    always: yes